name: Android Build Test

on:
  workflow_dispatch:

jobs:
  Android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          rm -rf .haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Compile hxcpp
        run: |
          cd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          key: cache-build-night
          path: |
            export/release/android/haxe/
            export/release/android/obj/

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: bfdi26mobile
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Clear Existing Build Cache
        uses: actions/github-script@v7
        with:
          script: |
            const caches = await github.paginate(
              github.rest.actions.getActionsCacheListForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100
              }
            );

            for (const cache of caches) {
              if (cache.key === "cache-build-night") {
                console.log(`Clearing ${cache.key}...`);

                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id
                });
              }
            }

            console.log("Build cache cleared.");
